language: php

php:
  - 7.0
  - 5.6

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
