language: php

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/php-coveralls -v
